import type { MetadataRoute } from 'next'

/**
 * Web app manifest (served at /manifest.webmanifest). Gives Android /
 * PWA "Add to Home Screen" the branded "CO" mark + name + theme color
 * instead of a generic screenshot. iOS home-screen uses app/apple-icon.png;
 * modern browser tabs use app/icon.svg; legacy + link-unfurl fallbacks
 * use app/favicon.ico. Icons here are generated by scripts/gen-icons.mjs.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Creator Outreach',
    short_name: 'Creator Outreach',
    description: 'Find, score, and reach out to the right creators — in one tracked queue.',
    start_url: '/',
    display: 'standalone',
    background_color: '#ffffff',
    theme_color: '#7C3AED',
    icons: [
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  }
}
