export const REGIONS: { code: string; flag: string; label: string }[] = [
  { code: 'US', flag: '🇺🇸', label: 'United States' },
  { code: 'GB', flag: '🇬🇧', label: 'United Kingdom' },
  { code: 'CA', flag: '🇨🇦', label: 'Canada' },
  { code: 'AU', flag: '🇦🇺', label: 'Australia' },
  { code: 'NZ', flag: '🇳🇿', label: 'New Zealand' },
  { code: 'IE', flag: '🇮🇪', label: 'Ireland' },
  { code: 'IN', flag: '🇮🇳', label: 'India' },
  { code: 'PH', flag: '🇵🇭', label: 'Philippines' },
  { code: 'SG', flag: '🇸🇬', label: 'Singapore' },
  { code: 'NG', flag: '🇳🇬', label: 'Nigeria' },
  { code: 'ZA', flag: '🇿🇦', label: 'South Africa' },
  { code: 'AE', flag: '🇦🇪', label: 'UAE' },
  { code: 'DE', flag: '🇩🇪', label: 'Germany' },
  { code: 'FR', flag: '🇫🇷', label: 'France' },
  { code: 'ES', flag: '🇪🇸', label: 'Spain' },
  { code: 'BR', flag: '🇧🇷', label: 'Brazil' },
  { code: 'MX', flag: '🇲🇽', label: 'Mexico' },
  { code: 'JP', flag: '🇯🇵', label: 'Japan' },
  { code: 'KR', flag: '🇰🇷', label: 'South Korea' },
  { code: 'ID', flag: '🇮🇩', label: 'Indonesia' },
]
