'use client'

import { motion } from 'motion/react'
import { ReactNode } from 'react'

/**
 * Bento layout for the "Everything you need" feature grid.
 *
 * Each card pairs a real product screenshot CROP (pre-generated by
 * scripts/crop-screenshots.py — pixel-perfect regions of the live
 * app) with a short title + description. Crops are bordered only by
 * the dark-screenshot edge itself, no chunky white frame, with a
 * subtle violet shadow underneath.
 */
export function BentoGrid({ children, className = '' }: { children: ReactNode; className?: string }) {
  return (
    <div className={`grid grid-cols-1 md:grid-cols-3 gap-3 md:gap-4 ${className}`}>
      {children}
    </div>
  )
}

export function BentoCard({
  title,
  description,
  icon,
  className = '',
  visual,
  delay = 0,
}: {
  title: string
  description: string
  icon: ReactNode
  className?: string
  visual?: ReactNode
  delay?: number
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 24 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.3 }}
      transition={{ duration: 0.6, delay, ease: 'easeOut' }}
      whileHover={{ y: -4, boxShadow: '0 28px 56px -16px rgba(124,58,237,0.40)' }}
      // Glass card on charcoal: subtle white tint + backdrop blur, ring
      // in the brand violet at low opacity. Aurora + meteors show
      // through. Hover brightens the ring.
      className={`group relative overflow-hidden rounded-2xl bg-white/[0.04] backdrop-blur-md ring-1 ring-white/10 hover:ring-brand/50 transition-all flex flex-col shadow-[0_10px_40px_-20px_rgba(0,0,0,0.4)] ${className}`}
    >
      {/* Soft violet/cyan hover wash */}
      <div className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none bg-gradient-to-br from-brand/10 via-transparent to-brand-2/10" />

      {visual && <div className="relative px-5 pt-5 pb-3">{visual}</div>}

      <div className="relative px-5 pb-5 pt-3 flex-1">
        <div className="flex items-center gap-2.5 mb-2">
          <div className="w-7 h-7 rounded-md bg-brand/15 border border-brand/30 flex items-center justify-center text-brand">
            {icon}
          </div>
          <h3 className="text-sm font-semibold text-foreground tracking-tight">{title}</h3>
        </div>
        <p className="text-[13px] text-muted-foreground leading-relaxed">{description}</p>
      </div>
    </motion.div>
  )
}

// ─────────────── visuals — pre-cropped real screenshots ───────────────

/**
 * Renders a pre-cropped screenshot. No border, just a rounded clip
 * and a soft violet-tinted shadow. Hover scales subtly (in addition
 * to the parent card lifting).
 *
 * `position` is the CSS object-position (e.g. 'top', 'left top') —
 * only matters when the displayed aspect ratio is tighter than the
 * source's, in which case object-cover trims along the configured
 * axis. Defaults to 'top' so we always show the meaningful header
 * region first.
 */
function CropImage({
  src,
  alt,
  position = 'top',
  className = '',
}: {
  src: string
  alt: string
  position?: string
  className?: string
}) {
  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.97 }}
      whileInView={{ opacity: 1, scale: 1 }}
      viewport={{ once: true, amount: 0.3 }}
      transition={{ duration: 0.5, ease: 'easeOut' }}
      className={`relative rounded-xl overflow-hidden shadow-[0_18px_45px_-18px_rgba(76,29,149,0.30),0_8px_24px_-12px_rgba(0,0,0,0.20)] ${className}`}
    >
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={src}
        alt={alt}
        className="block w-full h-full object-cover"
        style={{ objectPosition: position }}
      />
    </motion.div>
  )
}

// 1 — Smart search · top of Results page (search bar + tabs + first rows)
export function SearchVisual() {
  return <CropImage src="/screenshots/bento-search.png" alt="Search results across platforms" className="aspect-[2472/950]" />
}

// 2 — AI fit scoring · Channel + Fit Score columns showing colored chips
export function ScoringVisual() {
  return <CropImage src="/screenshots/bento-fit.png" alt="AI fit scoring chips" className="aspect-[870/940]" />
}

// 3 — Built-in CRM · right-side columns of the real Outreach table
// (Product / Reached / Status / Medium). The Status pill column with
// Successful / Open / Rejected gives full CRM context, not isolated
// cells like the previous tighter crop.
export function CrmVisual() {
  return <CropImage src="/screenshots/bento-status.png" alt="CRM table with status pills" className="aspect-[1110/700]" />
}

// 4 — Smart follow-up cadence · the leads list from Follow-ups page.
// Skipped the priority KPI cards (which read as analytics) and
// focused on the rows showing "6D LATE" red badges + purple
// "Followed up" buttons — the actual cadence-system signal.
export function CadenceVisual() {
  return <CropImage src="/screenshots/bento-priority.png" alt="Follow-up leads with late badges" className="aspect-[2810/760]" />
}

// 5 — Analytics + custom metrics · KPI cards + status breakdown
export function AnalyticsVisual() {
  return <CropImage src="/screenshots/bento-analytics.png" alt="Analytics dashboard" className="aspect-[2822/720]" />
}
